openapi: 3.0.3
info:
  title: Category Restful API
  description: Category Restful API
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/api'
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
    CreateOrUpdateCategory:
      type: object
      properties:
        name:
          type: string
    BaseResponse:
      type: object
      properties:
        code:
          type: number
        status:
          type: string
  parameters:
    CategoryId:
      name: categoryId
      in: path
      description: Category Id
paths:
  /categories:
    get:
      tags:
        - Category API
      summary: List all categories
      responses:
        200:
          description: List all categories
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponse'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/Category'
    post:
      tags:
        - Category API
      summary: Create New Category
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrUpdateCategory'
      responses:
        200:
          description: Success Create Category
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    $ref: '#/components/schemas/Category'
  /categories/{categoryId}:
    parameters:
      - $ref: '#/components/parameters/CategoryId'
    get:
      summary: Get Category by Id
      responses:
        200:
          description: success get category
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponse'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/Category'
    put:
      summary: Update category by id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrUpdateCategory'
      responses:
        200:
          description: Success get category
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    $ref: '#/components/schemas/CreateOrUpdateCategory'
    delete:
      summary: Delete category by id
      responses:
        200:
          description: Success delete category
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponse'